package enums;

public enum SubjectsSAM {
    DISCRETE_STRUCTURES,
    CALCULUS1,
    CALCULUS2,
    LINEAR_ALGEBRA,
    STATISTICS,
    CALCULUS3,
    DIFFERENTIAL_EQUATIONS,
    THEORETICAL_MECHANICS,
    NUMERICAL_METHODS,
    CODING_THEORY;
}
