package enums;

public enum SubjectsSCE {
    INORGANIC_CHEMISTRY,
    ENGLISH_FOR_CHEMIST,
    INTRODUCTION_TO_CHEMICAL_ENGINEERING,
    ORGANIC_CHEMISTRY1,
    PHYSICAL_CHEMISTRY1,
    ORGANIC_CHEMISTRY2,
    PHYSICAL_CHEMISTRY2,
    ANALYTICAL_CHEMISTRY,
    GENERAL_CHEMICAL_TECHNOLOGY,
    CHEMICAL_ENGINEERING_OF_ORGANICS;
}
