package enums;

public enum SubjectsSMGT {
    PHYSICS1,
    PHYSICS2,
    ELECTRICITY_AND_MAGNETISM,
    CHEMISTRY,
    STRENGTH_OF_MATERIAL,
    MOLECULAR_PHYSICS,
    QUANTUM_PHYSICS,
    TECHNICAL_MEASUREMENTS,
    FUNDAMENTALS_OF_SCIENTIFIC_RESEARCH,
    DESCRIPTIVE_GEOMETRY_AND_ENGINEERING_GRAPHICS;
}
