package enums;

public enum SubjectsBS {
    INTRODUCTION_TO_ACCOUNTING,
    FINANCIAL_ACCOUNTING,
    INTRODUCTION_TO_FINANCE,
    BUSINESS_COMMUNICATIONS,
    INTRODUCTION_TO_MARKETING,
    PRINCIPLES_OF_MICROECONOMICS,
    INTERMEDIATE_ACCOUNTING1,
    INTERMEDIATE_ACCOUNTING2,
    PRINCIPLES_OF_MACROECONOMICS,
    CORPORATE_FINANCE;
}
