package enums;

public enum SubjectsKMA {
    MANTIME_LAW1,
    SHIP_CONSTRUCTION,
    INTRODUCTION_TO_ENGINEERING_SUBJECTS,
    INTRODUCTION_TO_NAVIGATION_SUBJECTS,
    STABILITY_CONTROL1,
    TERRESTRIAL_NAVIGATION1,
    VOYAGE_PLANNING_AND_CONDUCTING1,
    BASIC_SAFETY_TRAINING_AND_SECURITY_AWARENESS,
    ELECTRONIC_NAVIGATION1,
    SHIPHANDLING_AND_MANEUVERING1;
}
