package enums;

public enum SubjectsSEPI {
    PETROLEUM_CHEMISTRY,
    PHYSICAL_GEOLOGY,
    INTRODUCTION_TO_PETROLEUM_ENGINEERING,
    THEORETICAL_AND_APPLIED_MECHANICS,
    STRENGTH_OF_MATERIALS,
    PRODUCTION_TECHNOLOGY,
    FLUID_MECHANICS,
    RESERVOIR_ENGINEERING,
    PETROLEUM_GEOLOGY,
    PIPELINE_ENGINEERING;
}
