package enums;

public enum SubjectsISE {
    PRINCIPLES_OF_MICROECONOMICS,
    PRINCIPLES_OF_MACROECONOMICS,
    INTRODUCTORY_STATISTICS1,
    INTRODUCTORY_STATISTICS2,
    INTRODUCTORY_CALCULUS1,
    INTRODUCTORY_CALCULUS2,
    MICROECONOMIC_THEORY,
    MACROECONOMIC_THEORY,
    ELEMENTS_OF_ECONOMETRICS1,
    ELEMENTS_OF_ECONOMETRICS2;
}
