package enums;

public enum SubjectsSNS {
    KAZAKH_LANGUAGE,
    RUSSIAN_LANGUAGE,
    ENGLISH_LANGUAGE,
    PHYSICAL_EDUCATION1,
    PHYSICAL_EDUCATION2,
    HISTORY_OF_KAZAKHSTAN,
    PHILOSOPHY,
    SOCIOLOGY,
    PSYCHOLOGY,
    POLITICAL_SCIENCE;
}
