package enums;

public enum SubjectsSG {
    ECOLOGY_AND_SUSTAINABLE_DEVELOPMENT,
    PHYSICAL_GEOLOGY,
    GEOLOGY_OF_OIL_AND_GAS,
    STRUCTURAL_GEOLOGY,
    INTRODUCTION_TO_GEOPHYSICS,
    GEODESY,
    PETROPHYSICS,
    GEOLOGY_OF_MINERAL_DEPOSITS,
    BASICS_OF_SUBOIL_USE,
    FUNDAMENTALS_OF_WELL_LOGGING;
}
